# Databricks notebook source
# COMPUTE: Serverless

# MAGIC %md
# MAGIC # Healthcare Interoperability Workshop — Genie Space
# MAGIC
# MAGIC Creates an AI/BI Genie space that lets users ask natural-language questions
# MAGIC against the workshop data. The Genie space is backed by the same tables as
# MAGIC the dashboard — ensuring both surfaces stay in sync.
# MAGIC
# MAGIC **Prerequisite:** All four workshop notebooks must have run first (or at minimum
# MAGIC the notebooks whose tables you want Genie to query).
# MAGIC
# MAGIC ---
# MAGIC **Synthetic data only — no PHI.**

# COMMAND ----------

# DBTITLE 1,Parameters
dbutils.widgets.text("catalog", "hls_workshop", "Workshop Catalog")
catalog = dbutils.widgets.get("catalog")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Genie Space Instructions
# MAGIC
# MAGIC The text below is the instructions prompt — it tells Genie what the data means,
# MAGIC what terms to use, and what questions to decline.

# COMMAND ----------

GENIE_INSTRUCTIONS = f"""
You are a data assistant for a healthcare interoperability workshop running on
Databricks. The workshop demonstrates four data integration patterns: JDBC
ingestion, CDA/CCDA XML file parsing, FHIR-to-OMOP transformation, and HL7v2
ADT message parsing. All data is synthetic (Synthea-generated) — no real PHI.

## Available Schemas

The `{catalog}` catalog contains these schemas:

### `ccda` — CDA/CCDA Clinical Documents
- `ccda_claims_raw` — raw parsed CCDA XML documents (one row per clinical document)
- `medications` — extracted medication records with patient name, city, medication_name

### `fhir` — FHIR-to-OMOP Transformation
- `person` — OMOP person table (demographics from FHIR Patient resources)
- `condition_occurrence` — OMOP conditions (from FHIR Condition resources)
- `procedure_occurrence` — OMOP procedures (from FHIR Procedure resources)
- `visit_occurrence` — OMOP visits (from FHIR Encounter resources)
- `condition_features` — per-patient chronic condition flags: diabetes_ind, hypertension_ind, substance_use_ind

### `hl7` — HL7v2 ADT Messages
- `parsed_hl7` — parsed HL7v2 admission messages with: patient_id, facility, admit_diagnosis, admit_location, message_type, parsed_at

### `audit` — Ingestion Audit Log
- `jdbc_ingests` — JDBC transfer history with row counts, timing, and source metadata

## UC Functions Available

The `{catalog}.functions` schema contains helper functions you can use in queries:
- `snomed_description(code)` — translates SNOMED CT codes to human-readable names
- `icd10_description(code)` — translates ICD-10-CM codes to descriptions
- `adt_event_description(code)` — translates HL7 ADT event codes (A01, A02, etc.)
- `age_from_dob(birth_date)` — computes age from date of birth
- `chronic_risk_tier(condition_count)` — classifies comorbidity burden as high/moderate/low/none
- `days_overdue_bucket(days)` — categorizes engagement status by days since encounter
- `hedis_measure_name(code)` — expands HEDIS measure codes to full names
- `is_valid_snomed(code)` — validates SNOMED code format
- `is_valid_icd10(code)` — validates ICD-10-CM code format

When a user asks about a diagnosis code or condition code, use the appropriate
description function to include the human-readable name in the response.

## Key Terms

- **CCDA**: Consolidated Clinical Document Architecture — XML format for clinical documents
- **FHIR**: Fast Healthcare Interoperability Resources — JSON-based healthcare data standard
- **OMOP CDM**: Observational Medical Outcomes Partnership Common Data Model — standardized schema for clinical research
- **HL7v2**: Health Level 7 Version 2 — pipe-delimited message format for real-time hospital events
- **ADT**: Admission, Discharge, Transfer — the category of HL7 messages tracking patient movement
- **SNOMED CT**: Standardized clinical terminology used in FHIR resources
- **ICD-10-CM**: International Classification of Diseases used in HL7 messages and claims

## Default Assumptions

- "Patient" refers to a synthetic patient generated by Synthea
- "Facility" in HL7 context means the sending hospital (e.g., MEMORIAL_COMMUNITY, FRANKLIN_COUNTY)
- "Condition" means a clinical diagnosis (not a data quality condition)
- When asked about diagnoses, include both the code and the human-readable description

## Out of Scope

- **Real patient data**: All data is synthetic. Decline questions that assume real PHI.
- **Cross-schema joins**: Do not join tables across schemas unless the user explicitly asks.
  Each schema represents a different interoperability pattern and the data is independent.
- **Predictive analytics**: This is a data integration workshop. Decline questions about
  predictions, risk scores, or ML models. Respond: "This workshop focuses on data
  integration patterns, not predictive analytics."
"""

print(GENIE_INSTRUCTIONS)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Create Genie Space

# COMMAND ----------

# DBTITLE 1,Create Genie Space via SDK
from databricks.sdk import WorkspaceClient

w = WorkspaceClient()

space_name = "Healthcare Interoperability Workshop"

tables = [
    # CCDA
    f"{catalog}.ccda.ccda_claims_raw",
    f"{catalog}.ccda.medications",
    # FHIR/OMOP
    f"{catalog}.fhir.person",
    f"{catalog}.fhir.condition_occurrence",
    f"{catalog}.fhir.procedure_occurrence",
    f"{catalog}.fhir.visit_occurrence",
    f"{catalog}.fhir.condition_features",
    # HL7
    f"{catalog}.hl7.parsed_hl7",
    # Audit
    f"{catalog}.audit.jdbc_ingests",
]

try:
    space = w.genie.create_space(
        title=space_name,
        description=GENIE_INSTRUCTIONS,
        table_identifiers=tables,
    )
    print(f"Genie space created: {space_name}")
    print(f"Space ID: {space.space_id}")
    print(f"Open at: #/genie/spaces/{space.space_id}")
except Exception as e:
    print(f"Could not create Genie space programmatically: {e}")
    print(f"\nCreate it manually:")
    print(f"  1. SQL > Genie Spaces > New")
    print(f"  2. Name: {space_name}")
    print(f"  3. Attach tables: {', '.join(tables)}")
    print(f"  4. Paste the instructions prompt from the cell above")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Sample Questions
# MAGIC
# MAGIC Test these after creating the space. They cover all four interoperability patterns.
# MAGIC
# MAGIC ### CCDA / Medications
# MAGIC 1. **"What are the most commonly prescribed medications?"**
# MAGIC    → Bar chart from `ccda.medications` grouped by `medication_name`
# MAGIC
# MAGIC 2. **"How many clinical documents were loaded?"**
# MAGIC    → Single number from `ccda.ccda_claims_raw`
# MAGIC
# MAGIC 3. **"Which cities have the most medication records?"**
# MAGIC    → Ranked list from `ccda.medications` grouped by `city`
# MAGIC
# MAGIC ### FHIR / OMOP
# MAGIC 4. **"How many patients have diabetes?"**
# MAGIC    → Count from `fhir.condition_features` where `diabetes_ind = 1`
# MAGIC
# MAGIC 5. **"What percentage of patients have both diabetes and hypertension?"**
# MAGIC    → Filtered count from `fhir.condition_features`
# MAGIC
# MAGIC 6. **"Show me the OMOP condition codes with their descriptions"**
# MAGIC    → Should use `functions.snomed_description()` to enrich `condition_occurrence`
# MAGIC
# MAGIC 7. **"How many patients are in each comorbidity risk tier?"**
# MAGIC    → Should use `functions.chronic_risk_tier()` against `condition_features`
# MAGIC
# MAGIC ### HL7 / Admissions
# MAGIC 8. **"Which facility has the most admissions?"**
# MAGIC    → Ranked list from `hl7.parsed_hl7` grouped by `facility`
# MAGIC
# MAGIC 9. **"What are the top admit diagnoses with their descriptions?"**
# MAGIC    → Should use `functions.icd10_description()` to enrich `parsed_hl7`
# MAGIC
# MAGIC 10. **"Show me all admissions at Memorial Community Hospital"**
# MAGIC     → Filtered table from `hl7.parsed_hl7` where `facility = 'MEMORIAL_COMMUNITY'`
# MAGIC
# MAGIC ### Cross-Pattern
# MAGIC 11. **"How many records did each workshop notebook produce?"**
# MAGIC     → Counts from all four schemas (one row per schema)
# MAGIC
# MAGIC 12. **"When was the last JDBC ingestion and how many rows were transferred?"**
# MAGIC     → Most recent row from `audit.jdbc_ingests`

# COMMAND ----------

# MAGIC %md
# MAGIC ## Deflection Examples
# MAGIC
# MAGIC These questions should be declined:
# MAGIC
# MAGIC 1. **"Which patients are most likely to be readmitted?"**
# MAGIC    → *"This workshop focuses on data integration patterns, not predictive analytics."*
# MAGIC
# MAGIC 2. **"Show me the real patient names"**
# MAGIC    → *"All data in this workshop is synthetic (Synthea-generated). No real patient data is present."*
# MAGIC
# MAGIC 3. **"Join the CCDA medications with the HL7 admissions"**
# MAGIC    → *"The CCDA and HL7 schemas contain data from different interoperability patterns
# MAGIC    with independent patient populations. A cross-schema join would not produce
# MAGIC    meaningful results."*
